apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: azure-devops-ocp-agent-bc-template
  annotations:
    description: "Azure Devops OpenShift self hosted agent buildconfig with optional custom CA bundle"
 
parameters:
 
  - name: NAMESPACE
    description: Namespace name
    required: true
 
  - name: GIT_URL
    description: GIT URL For Dockerfile
    required: true
    value: https://github.com/sunilgurnale/azure-devops-ocp-agent.git
 
  - name: OPENSHIFT_VERSION
    description: OpenShift client binary version
    value: "4.9.7"
 
  - name: AZP_AGENT_VERSION
    description: Azure agent version
    value: "2.187.2"
 
objects:
 
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: azure-devops-ocp-agent
      namespace: "${NAMESPACE}"
    spec:
      lookupPolicy:
        local: true
 
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: azure-devops-ocp-agent
      namespace: "${NAMESPACE}"
    spec:
 
      source:
        git:
          uri: ${GIT_URL}
        type: Git
 
      output:
        to:
          kind: ImageStreamTag
          name: azure-devops-ocp-agent:latest
 
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
          imageOptimizationPolicy: SkipLayers
          buildArgs:
            - name: OPENSHIFT_VERSION
              value: "${OPENSHIFT_VERSION}"
            - name: AZP_AGENT_VERSION
              value: "${AZP_AGENT_VERSION}"
 
